version: '3.8'

services:
  app:
    build: .
    ports:
      - "3002:3002"
    volumes:
      - .:/usr/src/app
      # Exclude node_modules from being mounted
      - /usr/src/app/node_modules
    env_file:
      - .env # Still load other variables from .env
    command: npm run dev # Or your development start script

