name: Docker Image CI - AWS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Build and push runfiting
      env:
        ECR_REGISTRY: 586794470915.dkr.ecr.eu-north-1.amazonaws.com
        ECR_REPOSITORY: spartcom/runfiting
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t runfiting:latest . # Zbuduj obraz bezpośrednio z Dockerfile
        docker tag runfiting:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker tag runfiting:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
